# Generated by Django 6.0.5 on 2026-06-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperformance',
            name='reopen_rate',
        ),
    ]
