# Generated by Django 6.0 on 2026-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
