# Generated by Django 6.0 on 2026-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
