# Generated by Django 6.0 on 2026-04-03 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemNotification',
            new_name='Notification',
        ),
        migrations.DeleteModel(
            name='GroupNotification',
        ),
    ]
