# Generated by Django 6.0 on 2026-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_systemnotification_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='uuid',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='piority',
            field=models.IntegerField(default=1),
        ),
    ]
