# Generated by Django 6.0 on 2026-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_uuid_notification_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='piority',
            new_name='priority',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
