# Generated by Django 6.0.3 on 2026-04-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_user'),
        ('projects', '0005_alter_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_project', to='projects.project'),
        ),
    ]
