# Generated by Django 6.0.3 on 2026-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_private',
            field=models.BooleanField(db_index=True, default=True, null=True),
        ),
    ]
