# Generated by Django 6.0.3 on 2026-04-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_private',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
