# Generated by Django 6.0.3 on 2026-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(default='Yêu cầu tham gia nhóm', max_length=255),
        ),
    ]
