# Generated by Django 6.0.3 on 2026-04-08 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_progress'),
        ('request', '0002_alter_request_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_project', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
