# Generated by Django 6.0.3 on 2026-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_reliability_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatarpath',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
