# Generated by Django 6.0.3 on 2026-04-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_avatar_userprofile_avatarpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatarpath',
            field=models.ImageField(blank=True, default='avatars/8.png', null=True, upload_to='avatars/'),
        ),
    ]
