# Generated by Django 6.0.5 on 2026-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_remove_skill_user_skill_category_alter_skill_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='created_at',
        ),
    ]
