# Generated by Django 6.0 on 2026-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='redoReason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
