# Generated by Django 6.0 on 2026-03-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_redoreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='estimation_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_helped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='lastupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='rated',
            field=models.CharField(blank=True, choices=[('bad', 'Bad'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reason',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='task',
            name='redoReason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('done', 'Done'), ('overdue', 'Overdue'), ('stuck', 'Stuck')], default='todo', max_length=15),
        ),
    ]
