# Generated by Django 6.0 on 2026-03-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reason',
        ),
    ]
