# Generated by Django 6.0 on 2026-03-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_warned',
            field=models.BooleanField(default=False),
        ),
    ]
