# Generated by Django 6.0.5 on 2026-05-26 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_is_warned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty_score',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='reopen_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('commented', 'Commented'), ('completed', 'Completed'), ('reopened', 'Reopened')], max_length=30)),
                ('old_value', models.CharField(max_length=255, null=True)),
                ('new_value', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
