# Generated by Django 6.0.5 on 2026-06-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_userskill_unique_together_and_more'),
        ('tasks', '0011_task_actual_minutes_task_ai_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.PositiveSmallIntegerField(default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='tasks.task')),
            ],
        ),
    ]
