# Generated by Django 6.0.5 on 2026-06-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_taskskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('in_review', 'In Review'), ('done', 'Done'), ('overdue', 'Overdue'), ('stuck', 'Stuck')], default='todo', max_length=15),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('progress_updated', 'Progress Updated'), ('commented', 'Commented'), ('completed', 'Completed'), ('approved', 'Approved'), ('reopened', 'Reopened')], max_length=30),
        ),
    ]
