# Generated by Django 6.0.5 on 2026-06-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_is_approved_task_progress_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='need_help',
            field=models.BooleanField(default=False),
        ),
    ]
