# Generated by Django 6.0.5 on 2026-06-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='project',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], max_length=20),
        ),
    ]
