# Generated by Django 6.0 on 2026-02-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
