# Generated by Django 6.0.3 on 2026-04-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name_normalized',
            field=models.CharField(db_index=True, max_length=225, null=True),
        ),
    ]
